### ISSUE TITLE
Compatibility with AliSoftware/Reusable lib ?

### ISSUE THREAD

**Issue by mackoj** [mergesort/GenericCells#1]
It could be great if your lib can be compatible with this [Reusable](https://github.com/AliSoftware/Reusable) lib.

This will allow other user to put `pod 'GenericCells/Reusable'` in our Podfile and be compatible with our stack.

`GenericCellReusable.swift`

Create this file in `src/AliSoftware_Reusable/`.

```swift
import Reusable

public protocol GenericCellReusable {
  func prepareForReuse()
}

public extension GenericCellReusable {
  func prepareForReuse() { }
}

public typealias GenericCellReusableProtocol = NibReusable & GenericCellReusable
```

`ReusableView.swift`

Move `ReusableView.swift` into another folder like `src/ReusableView/` in order to have multiple subspecies with `Cocoapods` that works

```swift
public typealias GenericCellReusableProtocol = ReusableGenericView
```

`GenericCollectionCell.swift`
```swift
public final class GenericCollectionCell<CustomView, ParentViewController>: UICollectionViewCell
where CustomView: UIView, CustomView: GenericCellReusableProtocol
```

`GenericTableCell.swift`
```swift
public final class GenericTableCell<CustomView>: UITableViewCell 
where CustomView: UIView, CustomView: GenericCellReusableProtocol
```

`GenericCells.podspec`
```ruby
  s.default_subspec = "Basic"

  # Extending GenericCells with AliSoftware/Reusable
  s.subspec "Reusable" do |ss|
    ss.source_files  = "src/AliSoftware_Reusable/*.swift"
    ss.dependency "GenericCells/Core"
    ss.dependency "AliSoftware/Reusable"
  end

  s.subspec "Core" do |ss|
    ss.source_files  = "src/*.{swift}"
    ss.framework  = "UIKit"
  end

  s.subspec "Basic" do |ss|
    ss.source_files  = "src/ReusableView/*.{swift}"
    ss.dependency "GenericCells/Core"
  end

```

**Comment by mackoj** [comment]
This should to the trick ;)

**Comment by mergesort** [comment]
Hey @mackoj. My apologies for the delay, I've been sick and haven't had the energy to devote to this. First of all, thank you, I appreciate the effort you put into this, this seems very well thought out. I'm very familiar with Reusable, it was partially what gave me the idea for this library.

I want to make sure that I'm understanding correctly. This change would give the option to use `Reusable`, not make it a dependency for everyone, right? I specifically wanted to avoid adding another dependency, but if it's an option, I think that's a very good compromise.

Let me know, and I'd be happy to follow up more. If everything makes sense, I'd be glad to accept a PR for the functionality.

Thanks again!

**Comment by mackoj** [comment]
Hi @mergesort,

This will give the option to use **AliSoftware/Reusable** with your library. The default subspec(**Basic**) will use your reusable implementation and the **Reusable** subspec will use **AliSoftware/Reusable** lib.

I didn’t make a PR because I think with more thought we can improve the implementation of **AliSoftware/Reusable** various protocol in your class but I didn’t take the time to do it.

I hope to work on it during the coming days/weeks. Thanks again for the library.

Cheers,

**Comment by mergesort** [comment]
Hey @mackoj. Thanks a lot! No rush, feel free to take your time, either way it's very appreciated.

Cheers!
